# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [38]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

In [39]:
import numpy as np

In [40]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [41]:
# Array NumPy
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 42 ms


In [42]:
# Python List
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 1.68 s


### Exercício 2

In [43]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0

In [44]:
array = np.arange(10)
array[5:8] = 0
array

array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9])

### Exercício 3

In [45]:
# Crie um array de 3 dimensões e imprima a dimensão 1

In [46]:
array3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])

array3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [47]:
array3[0]

array([[1, 2, 3],
       [4, 5, 6]])

### Exercício 4

In [48]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

In [49]:
matriz = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matriz)
print('Terceira linha da matriz:', matriz[2])
print('Primeira e segunda linha:', matriz[0], matriz[1])
print('Segunda e terceira coluna:', matriz.H[1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Terceira linha da matriz: [[7 8 9]]
Primeira e segunda linha: [[1 2 3]] [[4 5 6]]
Segunda e terceira coluna: [[2 5 8]
 [3 6 9]]


### Exercício 5

In [50]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [51]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Exercício 6

In [52]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [53]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

### Exercício 7

In [54]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B

In [55]:
A = np.array(np.arange(10))
print(A)
np.save('array_a', A)

[0 1 2 3 4 5 6 7 8 9]


In [56]:
B = np.load('array_a.npy')
print(B)

[0 1 2 3 4 5 6 7 8 9]


### Exercício 8

In [57]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

In [58]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

### Exercício 9

In [59]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [60]:
data = resp.json()
data

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30156',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30156/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30156/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30156/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/30156',
  'id': 534920251,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0MzUwNzA1NzIw',
  'number': 30156,
  'title': 'STY: some files in pandas/_libs/',
  'user': {'login': 'MomIsBestFriend',
   'id': 50263213,
   'node_id': 'MDQ6VXNlcjUwMjYzMjEz',
   'avatar_url': 'https://avatars0.githubusercontent.com/u/50263213?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/MomIsBestFriend',
   'html_url': 'https://github.com/MomIsBestFriend',
   'followers_url': 'https://api.github.com/users/MomIsBestFriend/followers',
   'follo

In [61]:
issues = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])
issues

number                                              title  \
0    30156                   STY: some files in pandas/_libs/   
1    30155                        TYP: pandas/_libs/algos.pyx   
2    30154  Issue on Pandas installation on Alpine:3.10 do...   
3    30153  TST: DataFrameGroupBy.shift Loses TimeZone in ...   
4    30152  No mechanism for indicating missing value in n...   
5    30151            WIP: Add numba engine for rolling apply   
6    30150  Modify hash(pd.NA) to avoid integer hash colli...   
7    30149                Consolidated Nanosecond Conversions   
8    30148  NoneType error during json_normalize due to sc...   
9    30147            CLN: Refactor pandas/tests/base - part3   
10   30146             Fix pd.NA `na_rep` truncated in to_csv   
11   30145  Fix NoneType error when pulling non existent f...   
12   30144  REF: use new pytables helper methods to de-dup...   
13   30141              CLN: convert str.format() to f-string   
14   30138  BUG: incorrect output of first('1M') in case i...   
15   30137   CLN/TYPE: window aggregation cleanups and typing   
16   30134  DataFrameGroupBy.shift Loses TimeZone in datet...   
17   30131        DOC: Cleaned docstrings in core/indexers.py   
18   30129                  WIP/DOC: Code style documentation   
19   30128                                CLN: ci code checks   
20   30126  df.hist(sharex=True) does not perform as expected   
21   30122  setting precision for display sometimes shows ...   
22   30114  API: add ignore_index keyword to .sort_* & .dr...   
23   30112                                      DEPR: msgpack   
24   30108  %s changed to fstring, single quotes in f stri...   
25   30107  When applied as style in to_excel(), 'vertical...   
26   30106                        df.to_excel gives TypeError   
27   30099                       CI: Unwanted patterns checks   
28   30092        Can't use named aggregation with resample.    
29   30091                BUG: preserve EA dtype in transpose   

                                               labels state  
0                                                  []  open  
1                                                  []  open  
2                                                  []  open  
3                                                  []  open  
4                                                  []  open  
5   [{'id': 527603109, 'node_id': 'MDU6TGFiZWw1Mjc...  open  
6   [{'id': 2822342, 'node_id': 'MDU6TGFiZWwyODIyM...  open  
7   [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
8                                                  []  open  
9   [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
10  [{'id': 2822342, 'node_id': 'MDU6TGFiZWwyODIyM...  open  
11                                                 []  open  
12  [{'id': 47229190, 'node_id': 'MDU6TGFiZWw0NzIy...  open  
13  [{'id': 106935113, 'node_id': 'MDU6TGFiZWwxMDY...  open  
14  [{'id': 53181044, 'node_id': 'MDU6TGFiZWw1MzE4...  open  
15  [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
16  [{'id': 986278782, 'node_id': 'MDU6TGFiZWw5ODY...  open  
17  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
18  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
19  [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
20  [{'id': 2413328, 'node_id': 'MDU6TGFiZWwyNDEzM...  open  
21                                                 []  open  
22  [{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgx...  open  
23  [{'id': 87485152, 'node_id': 'MDU6TGFiZWw4NzQ4...  open  
24  [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
25  [{'id': 49254273, 'node_id': 'MDU6TGFiZWw0OTI1...  open  
26  [{'id': 49254273, 'node_id': 'MDU6TGFiZWw0OTI1...  open  
27  [{'id': 106935113, 'node_id': 'MDU6TGFiZWwxMDY...  open  
28  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
29  [{'id': 849023693, 'node_id': 'MDU6TGFiZWw4NDk...  open

### Exercício 10

In [62]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas

In [63]:
import sqlite3 as sql

In [64]:
con = sql.connect('Users.db')

In [65]:
cur = con.cursor()

In [66]:
# Instrução para criar o banco de dados
sql_create = 'create table users' \
             '(id integer primary key,' \
             'nome varchar(50),' \
             'idade int)'

In [68]:
cur.execute(sql_create)

OperationalError: table users already exists

In [69]:
# Instrução para inserir dados no banco de dados
sql_insert = "insert into users values (?, ?, ?)"

In [70]:
data = [(1, 'Eduardo', 18),
        (2, 'Alana', 45),
        (3, 'Henrique', 50)]

con.executemany(sql_insert, data)

IntegrityError: UNIQUE constraint failed: users.id

In [71]:
con.commit()

In [72]:
# Instrução para selecionar os dados do banco de dados
sql_select = "select * from users"

In [73]:
cur.execute(sql_select)

In [74]:
data = cur.fetchall()
data

[(1, 'Eduardo', 18), (2, 'Edivânia', 45), (3, 'Alberto', 50)]

In [75]:
# Inserindo os dados em um DataFrame
users_df = pd.DataFrame(data, columns=[x[0] for x in cur.description])

users_df

id      nome  idade
0   1   Eduardo     18
1   2  Edivânia     45
2   3   Alberto     50

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>